number: 1
name: The first Virtual Midi Controller performance
tempo_config:
  min_bpm: 60
  max_bpm: 70
time_signature:
  beats_per_bar: 4
  beat_unit: 4
layers:
  - number: 1
    active: True
    channel: 0
    note_range_config:
      lower_key: "C-1"
      upper_key: "B2"
    velocity_range_config:
      max_velocity: 127
      min_velocity: 0
  - number: 2
    active: True
    channel: 1
    note_range_config:
      lower_key: "C3"
      upper_key: "G9"
    velocity_range_config:
      max_velocity: 127
      min_velocity: 0
    controller_changes:
      - continues_controller: "SUSTAIN"
        min: 0
        max: 127   
  - number: 3
    active: True
    channel: 2
    octave: 2
    note_range_config:
      lower_key: "C3"
      upper_key: "G9"
    velocity_range_config:
      max_velocity: 127
      min_velocity: 50      
  - number: 4
    active: True
    channel: 3
    note_range_config:
      lower_key: "C3"
      upper_key: "G9"
    velocity_range_config:
      max_velocity: 127
      min_velocity: 95      