number: 1
name: The first Virtual Midi Controller performance
tempo_config:
  min_bpm: 60
  max_bpm: 70
time_signature:
  beats_per_bar: 4
  beat_unit: 4
layers:
  - number: 1
    active: True
    channel: 0
    note_range_config:
      upper_key: "C-1"
      lower_key: "B3"
    velocity_range_config:
      max_velocity: 127
      min_velocity: 0
  - number: 2
    active: True
    channel: 1
    note_range_config:
      upper_key: "C4"
      lower_key: "G9"
    velocity_range_config:
      max_velocity: 127
      min_velocity: 0      